### ISSUE TITLE
Additional Info support for Banking Product Rate Tier

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/java-artefacts#107]
Add ``additionalInfo`` and ``additionalInfoUri`` to ``BankingProductRateTier``. Both fields should be treated as _optional_.

Specifically:
```
additionalInfo:
    type: string
    description: Display text providing more information on the rate tier.
additionalInfoUri:
    type: string
    description: Link to a web page with more information on this rate tier.
    x-cds-type: URIString
```
See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/107
