### ISSUE TITLE
Add Repayment Type and Loan Purpose to BankingProductLendingRate

### ISSUE THREAD

**Issue by JamesMBligh** [ConsumerDataStandardsAustralia/java-artefacts#108]
Update ``BankingProductLendingRate`` to include two new optional fields ``repaymentType`` and ``loanPurpose``.

```
BankingProductLendingRate
  type: object

// ... omitted for brevity   

    properties:
      repaymentType:
        type: string
        description: Options in place for repayments. If absent, the lending rate is applicable to all repayment types
        enum:
        - INTEREST_ONLY
        - PRINCIPAL_AND_INTEREST
      loanPurpose:
        type: string
        description: The reason for taking out the loan. If absent, the lending rate is applicable to all loan purposes.
        enum:
        - OWNER_OCCUPIED
        - INVESTMENT
```

See: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/48
See also: https://github.com/ConsumerDataStandardsAustralia/standards/issues/30
Decision record: https://confluence.csiro.au/display/DSB/Decision+-+Issue+%2348+-+Inclusion+of+repaymentType+and+loanPurpose+in+the+Product+detail+API
